# Generated by Django 5.2.5 on 2025-08-31 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_carrequest_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrequest',
            name='monthly_payment',
        ),
        migrations.RemoveField(
            model_name='carrequest',
            name='total_price',
        ),
        migrations.AddField(
            model_name='carrequest',
            name='local',
            field=models.TextField(blank=True),
        ),
    ]
